title = 'diSimplex tag databases'
app_log_level = 10
waitress_log_level = 10
flask_log_level = 10

[databases.fingerPieces]
baseUrl = 'fp'
logLevel = 10

[databases.diSimplex]
baseUrl = 'ds'
logLevel = 10

